###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombres":"Nuevo",
    "apellidos":"Nuevo",
    "cedula":"2560051945",
    "email":"jkzambrano2@espe.edu.ec",
    "telefono":"0935874596",
    "direccion":"La Lorena",
    "genero":"Masculino",
    "vehiculoarentar":"Busetas",
    "costos":"25$",
    "estado":"esperando"
}

###
GET http://localhost:9000/api/users HTTP/1.1
###

GET http://localhost:9000/api/users/64b9da4caf401a463e977ca9 HTTP/1.1

###
PUT http://localhost:9000/api/users/64b9da4caf401a463e977ca9 HTTP/1.1
Content-Type: application/json

{
    "nombres":"Kleber",
    "apellidos":"kleber",
    "cedula":"2350051930",
    "email":"jkzambrano2@espe.edu.ec",
    "telefono":"0939765584",
    "direccion":"coop carlos ruiz burneo",
    "genero":"Masculino",
    "vehiculoarentar":"Busetas",
    "costos":"25$"
}

###
DELETE  http://localhost:9000/api/users/64b9da4caf401a463e977ca9 HTTP/1.1

###
GET http://localhost:9000/api/users/estado/esperando

###
GET http://localhost:9000/api/users/estado/activo

###
GET http://localhost:9000/api/users/estado/inactivo